version: "3"

services:
  postgres:
    image: "postgres:14.7-alpine"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  pgdata:
